project:
  type: website

website:
  title: Portfolio
  navbar:
    left:
      - href: index.qmd
        text: Home
      - portfolio.qmd
      - href: about.qmd
        text: About Me

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true