project:
  type: website

website:
  title: Portfolio
  navbar:
    left:
      - href: index.qmd
        text: Home
      - portfolio.qmd
      - href: about.qmd
        text: About Me

format:
  html:
    grid:
      sidebar-width: 150px
      body-width: 1400px
      margin-width: 400px
    theme: cosmo
    toc: true
