---
title: "Home"

format:
  html:
    toc: true
    toc-location: right
    toc-title: "Contents"
    toc-expand: 4
---
<h4> Welcome to my portfolio of programming projects and competition submissions</h4>

# Featured Projects

<nav>
  <ul style="list-style-type:none; padding:0">
    <li style="display:inline; margin-right: 20px;"><a href="/posts/primes.html">Generating the nth prime number</a></li>
    <li style="display:inline; margin-right: 20px;"><a href="/posts/optimisation.html">Optimisation</a></li>
  </ul>
</nav>

# BPhO Computational Challenge 2024:

### Video Submission

<iframe width="800" height="400"
src="https://www.youtube.com/embed/ViT6NdrrbJo">
</iframe>

### Code and Explanations

<nav>
  <ul style="list-style-type:none; padding:0">
    <li style="display:inline; margin-right: 20px;"><a href="/posts/cchallenge1.html">Challenge 1 & 2: Analytical Drag-Free Projectile Model</a></li>
    <li style="display:inline; margin-right: 20px;"><a href="/posts/cchallenge2.html">Challenge 1 & 2: Analytical Drag-Free Projectile Model</a></li>
    <li style="display:inline; margin-right: 20px;"><a href="/posts/cchallenge3.html">Challenge 1 & 2: Analytical Drag-Free Projectile Model</a></li>
    <li style="display:inline; margin-right: 20px;"><a href="/posts/cchallenge4.html">Challenge 1 & 2: Analytical Drag-Free Projectile Model</a></li>
    <li style="display:inline; margin-right: 20px;"><a href="/posts/cchallenge5.html">Challenge 1 & 2: Analytical Drag-Free Projectile Model</a></li>
    <li style="display:inline; margin-right: 20px;"><a href="/posts/cchallenge6.html">Challenge 1 & 2: Analytical Drag-Free Projectile Model</a></li>
    <li style="display:inline; margin-right: 20px;"><a href="/posts/cchallenge7.html">Challenge 1 & 2: Analytical Drag-Free Projectile Model</a></li>
    <li style="display:inline; margin-right: 20px;"><a href="/posts/cchallenge8.html">Challenge 1 & 2: Analytical Drag-Free Projectile Model</a></li>
    <li style="display:inline; margin-right: 20px;"><a href="/posts/cchallenge9.html">Challenge 1 & 2: Analytical Drag-Free Projectile Model</a></li>   
    <li style="display:inline; margin-right: 20px;"><a href="/posts/cchallengee1.html">Challenge 1 & 2: Analytical Drag-Free Projectile Model</a></li>
  </ul>
</nav>